### ISSUE TITLE
NameError: global name 'c' is not defined

### ISSUE THREAD

**Issue by lieanu** [bdcht/amoco#25]
code:
- https://gist.github.com/lieanu/cb5d2c0bd3619f0c705c

``` python
import sys
import amoco
import amoco.system.raw
import amoco.system.core

def sym_exec_gadget_and_get_mapper(code, cpu):
    '''Taken from https://github.com/0vercl0k/stuffz/blob/master/look_for_gadgets_with_equations.py'''

    p = amoco.system.raw.RawExec(
        amoco.system.core.DataIO(code), cpu
    )

    try:
        blocks = list(amoco.lsweep(p).iterblocks())
    except:
        return None

    if len(blocks) == 0:
        return None

    mp = amoco.cas.mapper.mapper()
    for block in blocks:
        if block.instr[-1].mnemonic.lower() == 'call':
            p.cpu.i_RET(None, block.map)

        try:
            mp >>= block.map
        except Exception as e:
            pass

    return mp

if __name__ == "__main__":

    # adc bh, bh ; call qword ptr [rsi]
    import amoco.arch.x64.cpu_x64 as cpu
    bytes = "10ffff16".decode("hex")
    print sym_exec_gadget_and_get_mapper(bytes, cpu)
```

output:

``` shell
Traceback (most recent call last):structions [352]                              
  File "amoco_test2.py", line 38, in <module>
    print sym_exec_gadget_and_get_mapper(bytes, cpu)
  File "amoco_test2.py", line 24, in sym_exec_gadget_and_get_mapper
    p.cpu.i_RET(None, block.map)
  File "/usr/lib/python2.7/site-packages/amoco/code.py", line 32, in map
    self._map = mapper(self.instr)
  File "/usr/lib/python2.7/site-packages/amoco/cas/mapper.py", line 44, in __init__
    if not instr.misc['delayed']: instr(self)
  File "/usr/lib/python2.7/site-packages/amoco/arch/core.py", line 65, in __call__
    i_xxx(self,map)
  File "/usr/lib/python2.7/site-packages/amoco/arch/x64/asm.py", line 560, in i_ADC
    fmap[af]  = halfcarry(a,op2,c)
NameError: global name 'c' is not defined

```

**Comment by bdcht** [comment]
fixed by commit a805339
