### ISSUE TITLE
x64: typo (line missing) in MOVSXD decoding

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#53]
``` python
>>> str(cpu_x64.disassemble('\x48\x63\xd2'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "amoco/arch/core.py", line 197, in __call__
    return self(bytestring[s.mask.size/8:],**kargs)
  File "amoco/arch/core.py", line 190, in __call__
    i = s.decode(bytestring,e,i=self.__i,ival=b.ival)
  File "amoco/arch/core.py", line 437, in decode
    self.hook(obj=i,**kargs)
  File "amoco/arch/x64/spec_ia32e.py", line 629, in ia32_movsxd
    op2,data = getModRM(obj,Mod,RM,data,REX=(0,R,X,B))
NameError: global name 'R' is not defined
```

Proposed patch

``` python
--- a/amoco/arch/x64/spec_ia32e.py
+++ b/amoco/arch/x64/spec_ia32e.py
@@ -626,6 +626,7 @@ def ia32_arpl(obj,Mod,REG,RM,data,_inv):
 def ia32_movsxd(obj,Mod,REG,RM,data):
     op1 = getregR(obj,REG,64)
     # force REX.W=0 for op2 decoding:
+    W,R,X,B = getREX(obj)
     op2,data = getModRM(obj,Mod,RM,data,REX=(0,R,X,B))
     obj.operands = [op1, op2]
     obj.type = type_data_processing
```

**Comment by bdcht** [comment]
fixed by f357d0f.
