### ISSUE TITLE
Inconsistencies when using simultaneously multiple architectures

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#64]
``` python
>>> from amoco.arch.x64 import cpu_x64
>>> from amoco.cas.mapper import mapper
>>> cpu_x64.disassemble('\x77\x08')(mapper())
>>> from amoco.arch.x86 import cpu_x86
>>> cpu_x64.disassemble('\x77\x08')(mapper())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "amoco/arch/core.py", line 67, in __call__
    i_xxx(self,map)
  File "amoco/arch/x86/asm.py", line 503, in i_Jcc
    fmap[eip] = tst(fmap(cond),fmap[eip]+op1,fmap[eip])
  File "amoco/cas/expressions.py", line 39, in checkarg_numeric
    return f(self,n)
  File "amoco/cas/expressions.py", line 186, in __add__
    def __add__(self,n): return oper('+',self,n)
  File "amoco/cas/expressions.py", line 1201, in oper
    return op(opsym,l,r).simplify()
  File "amoco/cas/expressions.py", line 1216, in __init__
    raise ValueError("Size mismatch %d <> %d"%(l.size,r.size))
ValueError: Size mismatch 32 <> 64
```

We can see that after importing `x86`, decoding 64-bit instructions gets the semantics of 32-bit instructions.

**Comment by bdcht** [comment]
yes, its a known limitation (see #21).
