### ISSUE TITLE
x86 and x64: both arguments of PSLLQ (and others) can be registers

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#65]
``` python
>>> from amoco.arch.x64 import cpu_x64
>>> from amoco.cas.mapper import mapper
>>> i=cpu_x64.disassemble('\x66\x0f\xf3\xd3')
>>> str(i)
'psllq       xmm2, xmm3'
>>> i(mapper())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "amoco/arch/core.py", line 67, in __call__
    i_xxx(self,map)
  File "amoco/arch/x64/asm.py", line 1461, in i_PSLLQ
    res  = [v1<<src2.value for v1 in val1]
AttributeError: 'reg' object has no attribute 'value'
```

**Comment by bdcht** [comment]
thanks. fixed by commit 9e61be7
