### ISSUE TITLE
commit dac8e00b862eb6d87cc88dddd1e5316c67c1d798 broke something

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#95]
It took me some time to extract from the non-regression tests of plasmasm a short example.
```
from amoco.cas.mapper import mapper
from amoco.arch.x64 import env
machine = mapper()
machine[env.mem(env.rsp,size=64)] = env.lab('toto',size=64)
machine.M(env.mem(env.rsp,32))
```
worked well before commit dac8e00b862eb6d87cc88dddd1e5316c67c1d798 and now fails with the following error:
```
Traceback (most recent call last):
  File "(...)/amoco-machine-bug.py", line 5, in <module>
    machine.M(env.mem(env.rsp+16,32))
  File "(...)/amoco/amoco/cas/mapper.py", line 179, in M
    res = self._Mem_read(k.a, k.length, k.endian)
  File "(...)/amoco/amoco/cas/mapper.py", line 223, in _Mem_read
    elif p._is_ext and p._subrefs.get("mmio_r",None):
AttributeError: 'slc' object has no attribute '_subrefs'
```

**Comment by bdcht** [comment]
Fixed by [cd95a61](https://github.com/bdcht/amoco/commit/cd95a614186a6771c9c6b5b5dc791b46ae979404)
